global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8081']

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8082']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']